apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-run-
spec:
  pipelineRef:
    name: test-pipeline
  params:
    - name: url
      value: 'https://[git cloneしたいリポジトリのURL]'
    - name: SONAR_HOST_URL
      value: 'http://sonarqube:9000'
    - name: SONAR_PROJECT_KEY
      value: 'test-project'
    - name: IMAGE
      value: '[作成するコンテナイメージ名:タグ名]'
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: sonar-settings
      emptyDir: {}
