server:
  port: 8180

camel:
  component:
    kafka:
      group-id: ${CONSUMER_GROUP:customer-exporter}
      brokers: ${AMQS_BOOTSTRAP_SERVER:localhost:9092}
      auto-offset-reset: earliest
      break-on-first-error: true
      request-required-acks: -1
      max-in-flight-request: 5
      enable-idempotence: true
      retries: 2147483647
      auto-commit-enable: false
      allow-manual-commit: true

app:
  input-topic-name: ${INPUT_TOPIC_NAME:mytopic}
  output-topic-name: ${OUTPUT_TOPIC_NAME:myresult}
  url-deposit-entry-check: ${URL_DEPOSIT_ENTRY_CHECK:localhost:8183/camel/demo/deposit-entry-check}
  url-deposit-category: ${URL_DEPOSIT_CATEGORY:localhost:8183/camel/demo/deposit-category}
  url-check-available-deposit-amount: ${URL_CHECK_AVAILABLE_DEPOSIT_AMOUNT:localhost:8183/camel/demo/check-available-deposit-amount}
  url-deposit-allocation: ${URL_DEPOSIT_ALLOCATION:localhost:8183/camel/demo/deposit-allocation}
  url-deposit: ${URL_DEPOSIT:localhost:8183/camel/demo/deposit}
